### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by floating-cat** [floating-cat/S1-Next#14]
Current app architecture sucks, and `Account` model contains controller logic.

**Structure:**
- [x] Use [Data Binding](http://developer.android.com/tools/support-library/index.html).
- [x] Use Dagger 2 (DI) to avoid singletons.

**Dependencies**
- [x] Use Retrofit and RxAndroid instead of `AsyncTaskLoader`.
- [x] Use RxJava instead of Otto.

**Others:**
- [x] Separate `ToolbarDelegate` and `DrawerDelegate` from `BaseActivity`.
- [x] Reuse `ViewPager`'s logic for `ThreadListFragment`, `PostListActivity` and `FavouriteListFragment`.

**Abort:**
- Use MVP.
- Rewritten some code in Kotlin.

**Comment by floating-cat** [comment]
Start to do this after Google I/O 2015 (not sure whether they would [talk](https://events.google.com/io2015/schedule#day2/358c9f91-b6d4-e411-b87f-00155d5066d7) about MVP pattern or have any plan for Java 8, JVM language support).

**Comment by allenz8512** [comment]
I had practiced MVP pattern in an actual project and I don't think it's very useful in case of there is only one user interface per activity

**Comment by floating-cat** [comment]
The MVP pattern will decouple the logic and make testing easier (though current our app doesn't have any tests, I would start to write test case after refactoring).

But now I have choose to use the new data binding library instead MVP pattern because I think the official is better.
