### ISSUE TITLE
验证码验证失败

### ISSUE THREAD

**Issue by raidenii** [floating-cat/S1-Next#32]
最近论坛登陆时要求验证码，但是用app登陆时，即使输入了正确的验证码，app依然提示验证码错误，从而无法登陆。

**Comment by floating-cat** [comment]
这几天论坛换了新的验证码的形式，而客户端使用的是旧的验证码，所以导致登陆失败。（详细见论坛微博 http://weibo.com/u/5955106173）
不过我改了一个可以登陆的客户端的版本，你可以先借急用一下，不过不确保过几天能不能用（这句话绝对是真的）。
你可以到这里下载 http://pan.baidu.com/s/1jHKN4s2

**Comment by raidenii** [comment]
多谢！可以登陆了
